### PR TITLE
DoE unit tests and small bug fixes

### PR DESCRIPTION
**Pull request by JTPetter**
- Added comprehensive, verified unit tests for DoE analysis and design
- Fixed small bugs/inconsistencies that appeared in the process

### CODE REVIEW

**Comment by koenderks** [comment]
The unit tests seem to fail? But not because of the content, right?

**Comment by JTPetter** [comment]
Yes, not because of the content. Not sure what is going on, they pass locally, in my fork they fail only on Mac (something about NaN now being printed as empty string in a table), but here they don't even start.

**Comment by koenderks** [comment]
Well, I will just approve. Tbh, I didn't test it in any way but I think you probably agree with this procedure ;)

**Review by koenderks — APPROVED** [review]

**Review by koenderks — APPROVED** [review]

**Comment by JTPetter** [comment]
I mean, I definitely appreciate any testing of this module! In this case, I'm not too worried though, as this PR consists of tests... :) Thank you!

**Pull request merged**
