### PR TITLE
Rewriting stages

### PR DESCRIPTION
**Pull request by JTPetter**
- Rewrote stages so everything is one plot now, and more flexible so all control charts can be combined in one function in the future.
- Added manual calculation of SD for individual and MR chart, package could not handle MR-length values close to the sample size.
- Added options to select content of reports in var. chart individuals.
- Updated unit tests.

### CODE REVIEW

**Comment by JTPetter** [comment]
@vandenman fixed the unit tests

**Comment by vandenman** [comment]
Some of the test figures changed substantially, are you sure that is correct?

For example:

image

and

image

in addition, the name `titleless-plot-1-subplot-2.svg` suggests that these plots do not have a label. Is that correct?

**Comment by JTPetter** [comment]
@vandenman Yes, they should be correct, at least compared to Minitab (besides the red dots, but that its because we use different rules):

image

image

That the last group shows NA as the label is a bug, but that existed already previously and will be fixed in my next PR. I will then redo this test anyway, also because the dataset might be confusing. 

The fact that the plot does not have a title is because it is inside a container called "x-mR control chart" that contains both the plot and a table. So naming the plot would be redundant, but I'm open to suggestions to handle this differently...

**Comment by JTPetter** [comment]
This is the current setup with the container:

image

**Comment by vandenman** [comment]
> The fact that the plot does not have a title

I hadn't realized you actually wrote `"titleless-plot-1"` as the label in the unit test file, no then it should be okay.

**Review by vandenman — APPROVED** [review]

**Pull request merged**
