### PR TITLE
DoE analysis additions incl. RSM analysis

### PR DESCRIPTION
**Pull request by JTPetter**
Functionality to analyze RSM designs and some general DoE analysis things such as coding of predictors and blocks.

### CODE REVIEW

**Comment by JTPetter** [comment]
Have to figure out why the unit tests are failing, will try to update all my R packages

**Comment by JTPetter** [comment]
@vandenman manged to fix the unit test

**Review by vandenman — CHANGES_REQUESTED** [review]
Code looks fine, I found a few bugs, see below. The first looks the most severe, but you can probably judge this better. 

image

image

image

image

image


oh and perhaps the new CSV file `Qt 9 ...` should not end with `(1)`?

**Comment by JTPetter** [comment]
@vandenman 
1) I have removed the alias table for now, it seems to work rarely and I didn't look into this yet.
2) The one with the differing numbers of rows I will need more time for, not sure what is going on there but it also seems bit of an edge case hopefully?
3) The one with the blocks should be caught by the has.errors function testing for factor levels > 2. Somehow it does not work, do you have an idea?

**Comment by vandenman** [comment]
nope, no real idea why that would fail. But since we're on a tight schedule, I assume we have no more time to figure that out? The rest of the stuff looks fine to me so we can also merge this and make issues for the bugs I found so we fix them later.

**Comment by JTPetter** [comment]
Okay, let's do that. I've created the issues and assigned myself.

**Review by vandenman — APPROVED** [review]

**Pull request merged**
