### PR TITLE
Rewriting control charts

### PR DESCRIPTION
**Pull request by JTPetter**
- Wrote a single function for all control charts (x-bar, r, s, i, mr)
- Replaced and removed the old control chart functions everywhere (.xBarChart, .rChart, .IMRchart)
- Removed options to specify x-axis ticks in subgroups and individual charts (this should be in plot editing, so I did not include it in the new control chart function).
- Added option to specify stages to variable charts subgroups.
- Replaced decimals function with global decimal option .numDecimals
- Subgroups with one value are now displayed as having 0 range  or NA in the s/r-chart.
- Fix x-axis in subgroups sometimes displaying an NA, when pretty defines a last tick that goes beyond the provided axis labels.
- Fix x-axis in subgroups sometimes displaying labels twice or half values.
- Added labels to all plots that use stages, specifying the stage.
- Changed options to switch between xBar & R and IMR chart in Process Capability to radio button.
- Added error message when x-bar charts are selected and subgroup size is < 2 (only possible in wide format).
- Adjusted IMR chart in process capability, it should not be available in the wide format. Added X-bar & mR chart as alternative option.
- Implemented X-bar & mR chart, which is a moving range chart of the subgroup means.
- Fixes https://github.com/jasp-stats/jasp-issues/issues/2290 
- Fixes https://github.com/jasp-stats/jasp-issues/issues/1788 
- Fixes https://github.com/jasp-stats/jasp-issues/issues/2394
- Rule tables display the labels now when specified.
- Allowed ordinal variables for measurements in variable charts for individuals.
- Added functionality for individual charts to handle missing values.
- Added error message for autocorrelation chart when there are missing values.
- Added handling of missing values in stages to variable charts for individuals.
- Implemented option to specify stages but calculate limits over whole dataset, as in xbar & r chart by operator in gauge r&R.
- Some naming improvements and capitalization alignment.
- If a subgroup or axis label variable is provided for any control chart, the x axis title now has its name, if nothing is provided it is now "Sample".
- Make control limits solid lines when Phase 2 chart is created.
- Changed control chart subplots to always be vertically aligned in reports, never next to each other.
- Add option to specify fixed subgroup size when unequal, not simply take the largest. Changed input field and set default to actual sizes.
- Added option to use unbiasing constant or not to calculate s-chart.
- Added new extensive and verified unit tests for variable charts subgroups and variable charts individuals.

### CODE REVIEW

**Comment by JTPetter** [comment]
@koenderks @vandenman I understand this is a lot, but if either of you has time to look at this before the next release would be great!!

**Comment by koenderks** [comment]
@JTPetter Any idea why the unit test on ubuntu fails while the others do not?

**Comment by shun2wang** [comment]
@JTPetter  Could you also fix the i18n test? thanks:-)  just add `1$` `2$` into placeholders of  `gettextf("Removed %i %s that were not assigned to any stage.<br>", nDroppedStageRows, removalType)`

**Comment by JTPetter** [comment]
@shun2wang done, thank!
@koenderks No clue, and no access to any ubuntu machine, so not sure how I should go about fixing this...

**Comment by koenderks** [comment]
@JTPetter Could you then add `skip(“need to find out why this does not reproduce on Linux”)` (or something like that) in the code for this test?

**Comment by JTPetter** [comment]
@koenderks Okay, done!

**Review by koenderks — APPROVED** [review]

**Pull request merged**
